#!/usr/bin/env bash
set -e

sudo pacman -Syu

sudo pacman -S --needed git
sudo pacman -S --needed base-devel

ln -sf ~/workspace/dotfiles/config/bashrc ~/.bashrc
ln -sf ~/workspace/dotfiles/config/bash_profile ~/.bash_profile
 
YAY_DIR=~/workspace/yay
if [ ! -d $YAY_DIR ]; then
	git clone https://aur.archlinux.org/yay.git $YAY_DIR
	cd $YAY_DIR
	makepkg -si
fi

if ! [ -x "$(command -v gdm)" ]
then
	yay -S --needed gnome
	systemctl enable gdm
else
	echo "detected gdm, skipping"
fi
yay -S --needed gnome-tweaks

if ! [ -x "$(command -v cargo)" ]
then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
	echo "detected cargo, skipping"
fi
ln -sf ~/workspace/dotfiles/config/cargo/config ~/.cargo/

yay -S --needed watchexec
yay -S --needed fzf
yay -S --needed ripgrep
yay -S --needed wl-clipboard
yay -S --needed bash-completion

yay -S --needed ntp
# uncomment to update the clock
# sudo timedatectl set-timezone "$(curl --fail https://ipapi.co/timezone)"
# sudo ntpd -qg
# sudo hwclock --systohc

yay -S --needed vim
# dependency of coc-vim
yay -S --needed nodejs
yay -S --needed --asdeps npm
# must delete the existing sym link, or else it will create a nested directory
# https://unix.stackexchange.com/q/512139
rm -rf ~/.vim
ln -sf ~/workspace/dotfiles/config/vim ~/.vim
ln -sf ~/workspace/dotfiles/config/emacs/early-init.el ~/.emacs.d/early-init.el
ln -sf ~/workspace/dotfiles/config/emacs/init.el ~/.emacs.d/init.el

ln -sf ~/workspace/dotfiles/config/git ~/.config/

yay -S --needed qutebrowser
ln -sf ~/workspace/dotfiles/config/qutebrowser ~/.config/
