[theme]
file = "/home/josh/.config/sway/nord.toml"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"
warning_mem = 50
critical_mem = 80

[[block]]
block = "cpu"
warning = 50
critical = 80

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
format = "%a %b %e %I:%M"
