# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
if [ -x "$(command -v binps1)" ]
then
	PS1='$(binps1)'
else
	PS1='[\u@\h \W]\$ '
fi

source ~/.fzf.bash
source ~/workspace/dotfiles/config/fzf-bashrc

export QT_QPA_PLATFORM=wayland
