alias ls='ls --color=auto'

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
source ~/workspace/dotfiles/config/fzf-bashrc

source "$HOME/.cargo/env"

export EDITOR=vim

if [ -x "$(command -v binps1)" ]
then
	PS1='$(binps1 --theme nord)'
else
	PS1='[\u@\h \W]\$ '
fi
