# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

source ~/.fzf.bash
source ~/workspace/dotfiles/config/fzf-bashrc

export QT_QPA_PLATFORM=wayland
